// khai báo các name actions
export const FETCH_TINHTHANH = "FETCH_TINHTHANH";
export const FETCH_TINHTHANH_SUCCESS = "FETCH_TINHTHANH_SUCCESS";
export const FETCH_TINHTHANH_ERROR = "FETCH_TINHTHANH_ERROR";

export const FETCH_TRIEUCHUNG = "FETCH_TRIEUCHUNG";
export const FETCH_TRIEUCHUNG_SUCCESS = "FETCH_TRIEUCHUNG_SUCCESS";
export const FETCH_TRIEUCHUNG_ERROR = "FETCH_TRIEUCHUNG_ERROR";

export const FETCH_BENH = "FETCH_BENH";
export const FETCH_BENH_SUCCESS = "FETCH_BENH_SUCCESS";
export const FETCH_BENH_ERROR = "FETCH_BENH_ERROR";
